### ISSUE TITLE
Details on fields please

### ISSUE THREAD

**Issue by McF1y06** [alleen/magnetToTransmission#2]
Hi,

I can't manage to make it work.
I'm not sure if my preferences are well set.

In "IP", do I have to put http:// ?
In "URL", is it the transmission URL (/transmission/web/ by default) ? Or the path to the torrent repository on my NAS ?

I have tried many solutions but the download never started using  the "Send magnet to Transmission Server" shortcut. 

Thanks for your help.

**Comment by alleen** [comment]
Hi,

The "IP" didn't include "http://", You only need to write the server "ip" or "domain name" into this field.

The "URL" was the web rpc path of Transmission Server.

EX: 
Your transmission server full URL was : http://example.com:9091/transmission/web/.
IP: **example.com**
PORT: **9091**
PATH: **/transmission/rpc**

Thanks!!!

BR.

Alleen Wang
